### ISSUE TITLE
After changing language to german, reboot fails

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/asteroid-settings#14]
Using lenok nightly build from 2017/05/18 changing language in settings to german requires to reboot.
Boot than loops in LG bootscreen.
Image was flashed to userdata via "sudo fastboot flash userdata asteroid-image-lenok.ext4"
Only way to recover is enter fastboot manually by doing 45 angle leftup ro rightdown swipe and reflash.

**Comment by FlorentRevest** [comment]
Hi and thanks for reporting. I suspect your userdata partition is somehow corrupted.

Just to make sure, could you try to enter bootloader mode and run on your computer:
    fastboot boot zImage-dtb-lenok.fastboot -c debug-ramdisk
Then (after a few secs) use adb shell to run on the watch:
    source /machine.conf
    mount -t auto -o rw,noatime,nodiratime /dev/$sdcard_partition /sdcard
If you see an error such as:
    mount: mounting /dev/mmcblk0p21 on /sdcard/ failed: Invalid argument
https://github.com/AsteroidOS/meta-asteroid/commit/7917d6a0d08b9a74df57db4bd452084a872548df this commit should solve your problem. Then wait for a new nightly build and close the issue if it is effectively solved.

**Comment by FlorentRevest** [comment]
Mhhh, then this is a different problem. You should try to activate systemd persistent logging by following the instructions at the bottom of this page: https://asteroidos.org/wiki/boot-process/ and send the results of chroot /rfs /bin/journalctl if possible. Thanks for helping!

**Comment by eLtMosen** [comment]
Will do! Thank you for all your time.

**Comment by eLtMosen** [comment]
I have systemd logging set up but can not reproduce the error anymore...
Before creating this issue i tried to change language twice and had a boot loop.
Now with logging on i changed language for the fifth time now and all where booting perfect.
Closing, i will keep it in mind an reopen if it accours again.
