### ISSUE TITLE
when entering watchfacePage asteroid-settings closes

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/asteroid-settings#17]
Since some nightlybuilds it is not possible to select the watchface page from within the asteroid-settings.
I observe it since some weeks already on dory but only now have tried the recent nightly and see the problem persisted over some builds.

Edit, happens on fresh installed images so the problem is not (unofficial)watchface related.

**Comment by FlorentRevest** [comment]
Hi @eLtMosen,

Could you please verify if Qt 5.10.0 is being used in your build?
This issue was tracked in https://github.com/AsteroidOS/asteroid/issues/53 and should have been closed by the downgrade of Qt from 5.10.1 to 5.10.0. (tested to work on my watch)
Unfortunately, the build server hasn't released new builds since that change because of build errors and various changes to the base services. The problem you mention may already have been solved.

**Comment by eLtMosen** [comment]
how to check qt version on the watch? 
`qmake --version` or `qmake-qt5 --version` was my guess but not available.

**Comment by FlorentRevest** [comment]
Check the extension of the libq* files in /usr/lib

**Comment by eLtMosen** [comment]
hm, i don't see. 

`root@lenok:ceres# find /usr/lib -name "libq*"
/usr/lib/plugins/sqldrivers/libqsqlite.so
/usr/lib/plugins/sensorgestures/libqtsensorgestures_shakeplugin.so
/usr/lib/plugins/sensorgestures/libqtsensorgestures_plugin.so
/usr/lib/plugins/platforminputcontexts/libqtvirtualkeyboardplugin.so
/usr/lib/plugins/sensors/libqtsensors_sensorfw.so
/usr/lib/plugins/sensors/libqtsensors_generic.so
/usr/lib/plugins/audio/libqtmedia_pulse.so
/usr/lib/plugins/audio/libqtaudio_alsa.so
/usr/lib/plugins/generic/libqevdevmouseplugin.so
/usr/lib/plugins/generic/libqevdevtouchplugin.so
/usr/lib/plugins/generic/libqevdevtabletplugin.so
/usr/lib/plugins/generic/libqtuiotouchplugin.so
/usr/lib/plugins/generic/libqevdevkeyboardplugin.so
/usr/lib/plugins/playlistformats/libqtmultimedia_m3u.so
/usr/lib/plugins/iconengines/libqsvgicon.so
/usr/lib/plugins/sparqldrivers/libqsparqlendpoint.so
/usr/lib/plugins/sparqldrivers/libqsparqltracker.so
/usr/lib/plugins/platforms/libqminimal.so
/usr/lib/plugins/platforms/libqwayland-generic.so
/usr/lib/plugins/platforms/libqwayland-egl.so
/usr/lib/plugins/platforms/libqoffscreen.so
/usr/lib/plugins/platforms/libqvnc.so
/usr/lib/plugins/bearer/libqnmbearer.so
/usr/lib/plugins/bearer/libqconnmanbearer.so
/usr/lib/plugins/bearer/libqgenericbearer.so
/usr/lib/plugins/imageformats/libqsvg.so
/usr/lib/plugins/imageformats/libqjpeg.so
/usr/lib/libqtaround-dbus.so.0
/usr/lib/libqtaround-dbus.so.0.2.6
/usr/lib/qml/QtQml/StateMachine/libqtqmlstatemachine.so
/usr/lib/qml/QtQuick.2/libqtquick2plugin.so
/usr/lib/qml/Qt/labs/settings/libqmlsettingsplugin.so
/usr/lib/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.so
/usr/lib/qml/QtWayland/Compositor/libqwaylandcompositorplugin.so
/usr/lib/qml/QtQuick/LocalStorage/libqmllocalstorageplugin.so
/usr/lib/qml/QtQuick/Layouts/libqquicklayoutsplugin.so
/usr/lib/qml/QtQuick/Shapes/libqmlshapesplugin.so
/usr/lib/qml/QtQuick/VirtualKeyboard/Styles/libqtvirtualkeyboardstylesplugin.so
/usr/lib/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.so
/usr/lib/qml/QtTest/libqmltestplugin.so
/usr/lib/libqtaround.so.0.2.6
/usr/lib/libqtaround.so.1
root@lenok:ceres# 
`

**Comment by eLtMosen** [comment]
But you are right, i get the same journalctl output like in #53

`Feb 26 23:35:47 dory asteroid-launcher[495]: unsleepDisplay
Feb 26 23:35:55 dory asteroid-launcher[495]: Using the 'wl-shell' shell integration
Feb 26 23:35:56 dory booster-qtcomponents-qt5[554]: Using Wayland-EGL
Feb 26 23:35:58 dory asteroid-launcher[495]: QWaylandGLContext::makeCurrent: eglError: 3009, this: 0x1fbcfd8
Feb 26 23:35:58 dory asteroid-launcher[495]: Can't make current GL context
Feb 26 23:35:58 dory asteroid-launcher[495]: QOpenGLTexturePrivate::destroy() called without a current context.
Feb 26 23:35:58 dory asteroid-launcher[495]: Texture has not been destroyed
Feb 26 23:35:58 dory asteroid-launcher[495]: QOpenGLTexturePrivate::destroy() called without a current context.
Feb 26 23:35:58 dory asteroid-launcher[495]: Texture has not been destroyed
Feb 26 23:35:58 dory /usr/libexec/mapplauncherd/booster-qtcomponents-qt5[554]: Boosted process (pid=555) was terminated due to signal 11
Feb 26 23:35:58 dory invoker[657]: error: Can't send signal 11 to application [555]: No such process
`

**Comment by eLtMosen** [comment]
solved (for me) at least as of nightly 20180301
