### ISSUE TITLE
WallpaperPage has wrong default wallpaper

### ISSUE THREAD

**Issue by romainreignier** [AsteroidOS/asteroid-settings#2]
On first use, the "checked" wallpaper is `Ipswich_is_THAT_way_by_simon.hedge` instead of `flatmesh`.
https://github.com/AsteroidOS/asteroid-settings/blob/master/WallpaperPage.qml#L28

**Comment by FlorentRevest** [comment]
Thanks for reporting, fixed by https://github.com/AsteroidOS/asteroid-settings/commit/e3ff2770511a589ae012de24373242a0e3c8623b
