### ISSUE TITLE
Show active watchface in wallpaper selection over active wallpaper

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/asteroid-settings#24]
Rough algorithm
- When the wallpaper list is displayed, the current active wallpaper has the current active watchface displayed over/on it to instantly see the current state.
- user clicks on a new wallpaper
- currently a round checkmark is shown, i addition, display the current active watchface and remove it from previously selected wallpaper.
- Maybe for even better comparison, show the watchface twice, on newly selected wallpaper and previous. Nut that only makes sense if the wallpapers are both displayed on screen.

This helps the user to evaluate the choice without having to switch to Home/Watchface screen and navigate all the way back to settings->wallpaper to try the next one.
It also would add side by side comparison possibility in WYSIWYG style.

**Comment by FlorentRevest** [comment]
Mhh I think it makes sense to draw the watchface on the selected wallpaper (and maybe vice versa, add the wallpaper when selecting a watchface maybe) to let the user test quickly a few options.
However I think that showing it twice would get confusing

**Comment by eLtMosen** [comment]
Yes, twice might indeed be confusing.
Another problem could be that the wallpapers are not square shaped in the list, which is nice since more wallpapers are displayed on screen that way. But since the watchfaces are square i would favour to display them in square aspect ratio fitted to width of the wallpaper but cut height off in the same manner as the wallpapers are.
If that is possible.

**Comment by eLtMosen** [comment]
I consider the solution we have introduced in https://github.com/AsteroidOS/asteroid-settings/pull/40 as solution to this issue.
This issue sparked the idea to show wallpaper previews on the Watchfaces selection page and has thus served it purpose to find a way to make watchface and wallpaper combinations more easy to combine.
In case someone thinks different and actually wants watchface previews on top of the wallpaper selector items, feel free to reopen this issue.
