### ISSUE TITLE
Idea: Move display related settings to own page.

### ISSUE THREAD

**Issue by MagneFire** [AsteroidOS/asteroid-settings#26]
The additions of Tilt-to-wake and Always on display make the settings list rather long. I would like to propose a change where these options and the brightness setting is moved to its own page.

Here is the state of it currently
![Screenshot_20200817_212702](https://user-images.githubusercontent.com/7857908/90436624-4cd47480-e0d1-11ea-9cc1-f22a949ab238.jpg)

The Switch component(https://github.com/AsteroidOS/qml-asteroid/blob/master/src/controls/qml/Switch.qml) is replaced by something else which I think fits the overall design of AsteroidOS better (https://github.com/MagneFire/asteroid-settings/blob/displaypage/NewSwitch.qml). Obviously, this change would be applied to qml-asteroid when/if merged.

Feedback of this is welcome ;)

**Comment by jrtberlin** [comment]
Introducing category setting pages is obviously a good idea. 
That said, I think the spacing between entries could be larger and it would look more polished if the yes/no buttons would have the same size as the +/- buttons.

**Comment by MagneFire** [comment]
ok, here is another one.
Replace the enable/disable buttons to something more obvious.
Also the (+) button and the checkbox icons should be aligned now.
And the spacing is increased slightly.

![Screenshot_20200817_235841](https://user-images.githubusercontent.com/7857908/90448608-00dffa80-e0e6-11ea-8937-3920feb35980.jpg)

**Comment by MagneFire** [comment]
Another screenshot, but instead of hiding tilt-to-wake when it is not available. Just change the opacity and strike through the text. This indicates that the current build has tilt-to-wake support, but on the current platform it isn't working.

![Screenshot_20200818_191002](https://user-images.githubusercontent.com/7857908/90547428-cc267e80-e18b-11ea-8d02-387aa9542d52.jpg)
