### ISSUE TITLE
About: Add more information.

### ISSUE THREAD

**Issue by MagneFire** [AsteroidOS/asteroid-settings#33]
It would be great to see more system information on the about page.

Things that might be useful are:
- Uptime (updated every second)
- Qt version info
- Android base build (?)
- Kernel version
- Free space
- ...

**Comment by FlorentRevest** [comment]
If I remember correctly nemo-qml-plugin-systemsettings already has handy QML components for some of these. Worth having a look

**Comment by eLtMosen** [comment]
Relaying from Matrix chat.
User totalsonic1 wrote a wish list:

one feature request that I figure should be easier than most wish list items to add is to make the About screen in Settings app a lot more useful. Currently it only shows the Asteroid OS logo and 1.1 Nightly - but given that numerous versions have had that version label for about 2 years now that isn't really valuable info. So at minimum I'd like to request the build date of the installed image added. After that device info would be helpful: name and codename of watch, amount of memory in use and total available ram, amount of storage in use and total available rom, kernel version, display dimensions in pixels.  Thanks to the devs for consideration of this!

**Comment by beroset** [comment]
Consolidated wish list:
- [ ] Uptime (updated every second)
- [ ] Qt version info
- [ ] Android base build (?)
- [ ] Kernel version
- [ ] Free space
- [ ] build date of the installed image
- [ ] name of watch
- [ ] codename of watch
- [ ] memory in use
- [ ] total available RAM
- [ ] storage in use
- [ ] total available ROM
- [ ] Display dimensions in pixels

**Comment by beroset** [comment]
Now that https://github.com/AsteroidOS/asteroid-settings/pull/74 is merged, everything on the wish list (and more!) is covered except for displaying the Android base version.  Are we ready to close this issue?
