### ISSUE TITLE
Watchface and applauncher selection is slow

### ISSUE THREAD

**Issue by MagneFire** [AsteroidOS/asteroid-settings#38]
These pages load the qml files using a `Loader`. We might consider changing this as this is quite resource intensive, resulting in sluggish behavior.
Discussed with @FlorentRevest and @eLtMosen we came up with the following potential solutions:
- Check/enable disk caching  (https://doc.qt.io/qt-5/qmldiskcache.html)
- Create a daemon that watches using inotify for changes in watchface and applauncher folders and generate images (thumbnails) for those to be loaded into the settings app.

**Comment by eLtMosen** [comment]
An even more performance friendly solution would be to have static images of a screenshot with background transparency supplied by each watchface and use those in case the first route in the user path after startup is to navigate to the WF selector.
- In case the to be created daemon has not generated those screenshots/thumbnails during current runtime, those could be used to start up the watchface selector as fast as the wallpaper selector does.
- Then as soon as the user selects one of the WF, update it from thumbnail to "live view".
- In that case only one WF would be generated/updated at a time, preventing the slow upstart and sequential update of all WF.
. Those premade thumbnails could have the advantage to showcase a WF in its "sweet spot". Many WF have a time where the hands have a especially nice looking position.

**Comment by eLtMosen** [comment]
Aaaand fixed.
https://github.com/AsteroidOS/asteroid-settings/pull/40
https://github.com/AsteroidOS/asteroid-settings/pull/39
