### ISSUE TITLE
The checkbox for accepting changes is not visible (tetra)

### ISSUE THREAD

**Issue by Etua** [AsteroidOS/asteroid-settings#5]
Checkbox (in the image present under languages) is not visible, instead I see five language choices (second image). After clicking the space where the button should be, the watch has made a reboot and the language has been eventually changed, but the bug remained. The same thing occurs in other setting menus like date.

![](https://asteroidos.org/wp-content/uploads/2016/12/settings-language.png)
![img_20161211_002948](https://cloud.githubusercontent.com/assets/13040148/21076932/e490a57c-bf39-11e6-9453-04dd0f613b2e.jpg)

**Comment by FlorentRevest** [comment]
This issue (with some other graphical glithces on tetra) has been fixed a couple of weeks ago.
