### ISSUE TITLE
Nightstand - charging status only screen

### ISSUE THREAD

**Issue by Cambi0nn** [AsteroidOS/asteroid-settings#96]
I would (also) like to request an option in nightstand mode that keeps the screen off (to prevent a light-source while sleeping. Some people sleep best in total darkness), beside a small indication that it's still charging so you don't have to touch the watch to check (which, with the sometimes tricky pogo-pins, can at times deconnect it from charging).

For example with a singular low-brightness red pixel when under 90% turning green when above 90% but turns off when disconnected from the charger/dock. I'm not sure how that would go with things like backlight (but if I look at the always-on screen it looks quite dark outside of the white letters) and burn-in protection, so I'm open to other options/suggestions for a mode like this.

**Comment by beroset** [comment]
A very similar feature request on this is here:   https://github.com/AsteroidOS/asteroid/issues/131  and a PR is already submitted.  The single-pixel idea is interesting, though.

**Comment by beroset** [comment]
The optional "always on" for nightstand was merged in September 2023.
